version: '3.6'

services:
  catmap:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    command: "rails server -b 0.0.0.0"
  test:
    build: .
    volumes:
      - ./:/app
    command: "rails test"
  selenium:
    image: seleniarm/standalone-firefox
    ports:
      - 4444:4444/tcp
      - 7900:7900/tcp
    links:
      - catmap
  selenium-test:
    build: .
    command: "rspec"
    volumes:
      - ./:/app
    links:
      - selenium
