# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Simpletest' do
  before(:each) do
    @driver = Selenium::WebDriver.for(:remote, url: 'http://selenium:4444/wd/hub', capabilities: Selenium::WebDriver::Options.firefox)
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'simpletest' do
    @driver.get('http://catmap:3000/')
    Selenium::WebDriver::Wait.new(timeout: 30).until { @driver.find_element(:link_text, 'войти') }
    @driver.find_element(:link_text, 'войти').click
    @driver.find_element(:link_text, 'регистрация').click
    @driver.find_element(:id, 'user_email').click
    @driver.find_element(:id, 'user_email').send_keys('selenium' + rand(1..100).to_s + '@test.com')
    @driver.find_element(:id, 'user_password').send_keys('selenium')
    @driver.find_element(:id, 'user_password_confirmation').send_keys('selenium')
    @driver.find_element(:name, 'commit').click
    Selenium::WebDriver::Wait.new(timeout: 30).until { @driver.find_element(:css, '.add-cat-button') }
    @driver.find_element(:css, '.add-cat-button').click
    @driver.find_element(:id, 'title').click
    @driver.find_element(:id, 'title').send_keys('Selenium Cat')
    @driver.find_element(:id, 'description').send_keys('Test cat')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:css, '.button_to:nth-child(1) > button').click
    @driver.find_element(:css, '.button_to > button').click
  end
end
